Repository HuguesRomain/mars_exodus_2060, pull requests merged in 2020-06, with the labels that each got.

#3 Initialisation de la navigation global
  README.md
  package.json
  src/exodus/App.tsx
  src/exodus/apps/calandar/index.tsx
  src/exodus/apps/calendar/index.tsx
  src/exodus/apps/home/index.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/internal-router.ts
  src/exodus/main.js
  src/exodus/services/calandar.d.ts
  src/exodus/services/calendar.d.ts
  src/exodus/startup.tsx
  src/index.tsx
  src/styles/assets/icons/icons.js
  src/styles/atoms/icons.tsx
  src/styles/global.ts
  tsconfig.json
  yarn.lock
Labels: To Review

#8 bus
  src/exodus/utils/bus.ts
Labels: mergeable

#7 Initialisation app calendar
  package.json
  src/exodus/apps/calendar/components/atoms/ActivityItem.tsx
  src/exodus/apps/calendar/components/molecules/ActivityList.tsx
  src/exodus/apps/calendar/components/organismes/Calendar.tsx
  src/exodus/apps/calendar/components/organismes/test.css
  src/exodus/apps/calendar/index.tsx
  src/exodus/main.js
  src/exodus/services/calendar.d.ts
  src/react-app-env.d.ts
  src/styles/const.ts
  yarn.lock
Labels: wip

#14 Navbar
  package.json
  src/exodus/apps/auth/index.tsx
  src/exodus/apps/calendar/index.tsx
  src/exodus/apps/home/index.tsx
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/social/index.tsx
  src/exodus/components/molecules/mobileHeader.tsx
  src/exodus/components/navbar/atoms/IconMarsExodus.tsx
  src/exodus/components/navbar/atoms/labeledIcon.tsx
  src/exodus/components/navbar/atoms/themePicker.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/components/navbar/organisms/planetDate.tsx
  src/exodus/main.js
  src/exodus/services/calendar.d.ts
  src/exodus/utils/checkWindowSize.tsx
  src/index.tsx
  src/styles/assets/LogoMarsExodus.png
  src/styles/assets/icons/icons.js
  src/styles/assets/icons/icons.tsx
  src/styles/atoms/icons.tsx
  src/styles/const.ts
  yarn.lock
Labels: wip

#11 Application de profile
  src/exodus/apps/profile/atoms/labeledInfo.tsx
  src/exodus/apps/profile/atoms/welcomeMessage.tsx
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/profile/molecules/header.tsx
  src/exodus/apps/profile/molecules/identityCard.tsx
  src/exodus/apps/profile/organisms/infoSection.tsx
  src/exodus/apps/profile/organisms/ticketSection.tsx
  src/exodus/components/atoms/button.tsx
  src/exodus/components/molecules/mobileHeader.tsx
  src/exodus/components/molecules/subNavigation.tsx
  src/exodus/components/navbar/atoms/labeledIcon.tsx
  src/exodus/components/navbar/atoms/themePicker.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/main.js
  src/exodus/utils/uriUtils.ts
  src/styles/assets/icons/icons.tsx
  src/styles/assets/pics/exempleProfile.png
  src/styles/assets/pics/fingerprint.png
  src/styles/assets/pics/signature.png
  src/styles/assets/pics/ticket.png
  src/styles/atoms/icons.tsx
  src/styles/const.ts
Labels: wip

#13 social page begin
  src/assets/icons.svg
  src/exodus/apps/social/MobileComments.tsx
  src/exodus/apps/social/atoms/Comment.tsx
  src/exodus/apps/social/atoms/Like.tsx
  src/exodus/apps/social/atoms/Share.tsx
  src/exodus/apps/social/index.tsx
  src/exodus/apps/social/molecules/AddMedia.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/apps/social/organismes/SendComment.tsx
  src/exodus/services/social.d.ts
  src/exodus/utils/Icon.tsx
Labels: wip

#18 [css] update css calendar
  src/exodus/apps/calendar/components/atoms/ActivityItem.tsx
  src/exodus/apps/calendar/components/molecules/ActivityList.tsx
  src/exodus/apps/calendar/components/organismes/Calendar.tsx
  src/exodus/apps/calendar/components/organismes/test.css
Labels: wip

#17 Update Social Network
  src/exodus/apps/social/MobileComments.tsx
  src/exodus/apps/social/SocialPage.tsx
  src/exodus/apps/social/atoms/Avatar.tsx
  src/exodus/apps/social/atoms/Comment.tsx
  src/exodus/apps/social/atoms/Like.tsx
  src/exodus/apps/social/atoms/Share.tsx
  src/exodus/apps/social/index.tsx
  src/exodus/apps/social/molecules/AddComment.tsx
  src/exodus/apps/social/molecules/AddMedia.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/apps/social/organismes/SendComment.tsx
  src/exodus/apps/social/organismes/advertisement.tsx
  src/exodus/components/navbar/atoms/IconMarsExodus.tsx
  src/exodus/internal-router.ts
  src/exodus/utils/Icon.tsx
  src/styles/assets/icons/icons.tsx
  src/styles/assets/pics/bobafett.png
  src/styles/assets/pics/dune.png
  src/styles/atoms/icons.tsx
Labels: wip

#23 Tout plein de fix
  package.json
  src/exodus/apps/calendar/components/atoms/ActivityItem.tsx
  src/exodus/apps/calendar/components/molecules/ActivityList.tsx
  src/exodus/apps/calendar/components/organismes/Calendar.tsx
  src/exodus/apps/home/atomes/TimeCount.tsx
  src/exodus/apps/home/molecules/Timer.tsx
  src/exodus/apps/home/organismes/Header.tsx
  src/exodus/apps/profile/atoms/labeledInfo.tsx
  src/exodus/apps/profile/atoms/welcomeMessage.tsx
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/profile/molecules/identityCard.tsx
  src/exodus/apps/profile/organisms/ticketSection.tsx
  src/exodus/apps/social/MobileComments.tsx
  src/exodus/apps/social/SocialPage.tsx
  src/exodus/apps/social/atoms/Avatar.tsx
  src/exodus/apps/social/atoms/Comment.tsx
  src/exodus/apps/social/atoms/Like.tsx
  src/exodus/apps/social/atoms/Share.tsx
  src/exodus/apps/social/molecules/AddComment.tsx
  src/exodus/apps/social/molecules/AddMedia.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/apps/social/organismes/SendComment.tsx
  src/exodus/apps/social/organismes/advertisement.tsx
  src/exodus/components/atoms/button.tsx
  src/exodus/components/molecules/mobileHeader.tsx
  src/exodus/components/molecules/subNavigation.tsx
  src/exodus/components/navbar/atoms/labeledIcon.tsx
  src/exodus/components/navbar/atoms/themePicker.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/components/navbar/organisms/planetDate.tsx
  src/exodus/main.js
  src/exodus/oldMain.js
  src/exodus/startup.tsx
  src/exodus/utils/checkWindowSize.tsx
  src/index.tsx
  src/styles/assets/fonts/josefinSans.ttf
  src/styles/assets/fonts/josefinSansItalic.ttf
  src/styles/assets/icons/icons.tsx
  src/styles/const.ts
  src/styles/global.js
  yarn.lock
Labels: To Review

#27 [css] integration list of articles
  package.json
  src/exodus/apps/home/atomes/TimeRead.tsx
  src/exodus/apps/home/index.tsx
  src/exodus/apps/home/molecules/CarouselHead.tsx
  src/exodus/apps/home/organismes/CarouselInfo.tsx
  src/exodus/apps/home/organismes/CarouselItem.tsx
  src/exodus/apps/home/organismes/carousel.css
  src/exodus/components/atoms/button.tsx
  src/exodus/components/swipper.tsx
  src/react-app-env.d.ts
  src/styles/assets/icons/icons.tsx
  src/styles/atoms/icons.tsx
  yarn.lock
Labels: wip

#29 fix responsive to be adaptative
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/social/SocialPage.tsx
  src/exodus/apps/social/atoms/Comment.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/components/molecules/mobileHeader.tsx
  src/exodus/components/navbar/atoms/labeledIcon.tsx
  src/exodus/components/navbar/atoms/themePicker.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/context.tsx
  src/exodus/main.tsx
  src/exodus/startup.tsx
  src/exodus/utils/checkWindowSize.tsx
  src/styles/atoms/icons.tsx
Labels: To Review

#34 [css, js] fix desktop style and fix global swipper component
  src/exodus/apps/calendar/components/atoms/ActivityItem.tsx
  src/exodus/apps/calendar/components/molecules/ActivityList.tsx
  src/exodus/apps/calendar/components/organismes/Calendar.tsx
  src/exodus/apps/calendar/components/organismes/calendar.css
  src/exodus/apps/calendar/index.tsx
  src/exodus/apps/home/molecules/CarouselHead.tsx
  src/exodus/components/atoms/swipper.tsx
  src/styles/const.ts
Labels: wip
