Repository HuguesRomain/mars_exodus_2060, pull requests merged in 2020-07, with the labels that each got.

#9 Parcours d'authentification
  src/exodus/apps/auth/atoms/button.tsx
  src/exodus/apps/auth/atoms/input.tsx
  src/exodus/apps/auth/authSteps/register/finalStep.tsx
  src/exodus/apps/auth/authSteps/register/firstStep.tsx
  src/exodus/apps/auth/authSteps/register/secondStep.tsx
  src/exodus/apps/auth/authSteps/resetPassword/finalStep.tsx
  src/exodus/apps/auth/authSteps/resetPassword/firstStep.tsx
  src/exodus/apps/auth/authSteps/resetPassword/moodalResetPassword.tsx
  src/exodus/apps/auth/authSteps/resetPassword/secondStep.tsx
  src/exodus/apps/auth/index.tsx
  src/exodus/apps/auth/organisms/authCard.tsx
  src/exodus/apps/auth/style.ts
  src/exodus/apps/home/index.tsx
  src/exodus/apps/home/molecules/Timer.tsx
  src/exodus/apps/home/organismes/Header.tsx
  src/exodus/apps/home/organismes/carousel.css
  src/exodus/apps/home/organismes/carousels/carousel.css
  src/exodus/apps/home/organismes/map.tsx
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/profile/molecules/header.tsx
  src/exodus/components/atoms/button.tsx
  src/exodus/context.tsx
  src/exodus/internal-router.ts
  src/exodus/main.tsx
  src/exodus/services/auth.d.ts
  src/exodus/services/auth/auth.ts
  src/exodus/startup.tsx
  src/exodus/utils/accessStorage.ts
  src/styles/assets/icons/icons.tsx
  src/styles/assets/mobile/header.png
  src/styles/assets/pics/hero/hero_1.png
  src/styles/assets/pics/hero/hero_2.png
  src/styles/assets/pics/hero/hero_3.png
  src/styles/assets/pics/hero/hero_6.png
  src/styles/assets/pics/hero/hero_7.jpg
  src/styles/atoms/icons.tsx
  src/styles/const.ts
  src/styles/global.js
  yarn.lock
Labels: To Review

#42 [css, js] fix button and refacto the of code
  src/exodus/apps/home/organismes/Header.tsx
  src/index.tsx
Labels: bug

#38 [js] start of the connection to back
  src/exodus/apps/social/MobileComments.tsx
  src/exodus/apps/social/SocialPage.tsx
  src/exodus/apps/social/atoms/Comment.tsx
  src/exodus/apps/social/index.tsx
  src/exodus/apps/social/molecules/AddComment.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/apps/social/organismes/SendComment.tsx
  src/exodus/services/profile/profile.d.ts
  src/exodus/services/social.d.ts
  src/exodus/services/social/social.d.ts
  src/exodus/services/social/social.hook.ts
  src/styles/assets/icons/icons.tsx
Labels: wip

#41 Intégration des articles
  src/exodus/apps/home/article.tsx
  src/exodus/apps/home/atomes/TimeCount.tsx
  src/exodus/apps/home/atomes/TimeRead.tsx
  src/exodus/apps/home/atoms/TimeRead.tsx
  src/exodus/apps/home/index.tsx
  src/exodus/apps/home/molecules/Timer.tsx
  src/exodus/apps/home/molecules/itemCarouselPlaces.tsx
  src/exodus/apps/home/organismes/CarouselItem.tsx
  src/exodus/apps/home/organismes/carousels/carousels.tsx
  src/exodus/apps/home/organismes/map.tsx
  src/exodus/apps/home/place.tsx
  src/exodus/internal-router.ts
  src/exodus/main.tsx
  src/exodus/services/home.d.ts
  src/exodus/services/home.ts
  src/exodus/utils/uriUtils.ts
  src/styles/assets/icons/icons.tsx
  src/styles/atoms/icons.tsx
  src/styles/global.js
  yarn.lock
Labels: wip

#52 Implémentation de la timeline
  src/exodus/apps/calendar/components/organismes/Calendar.tsx
  src/exodus/apps/calendar/index.tsx
  src/exodus/apps/home/index.tsx
  src/exodus/apps/home/organismes/Header.tsx
  src/exodus/apps/home/pages/article.tsx
  src/exodus/apps/home/pages/place.tsx
  src/exodus/apps/profile/index.tsx
  src/exodus/apps/profile/organisms/infoSection.tsx
  src/exodus/apps/profile/organisms/ticketSection.tsx
  src/exodus/apps/social/SocialPage.tsx
  src/exodus/apps/social/organismes/CommentItem.tsx
  src/exodus/apps/social/organismes/PostItem.tsx
  src/exodus/components/atoms/button.tsx
  src/exodus/components/atoms/pulser.tsx
  src/exodus/components/molecules/subNavigation.tsx
  src/exodus/components/navbar/data/index.ts
  src/exodus/components/navbar/index.tsx
  src/exodus/components/timeline/molecule/popup.tsx
  src/exodus/components/timeline/organisms/step.tsx
  src/exodus/components/timeline/step.tsx
  src/exodus/components/timeline/timeline.tsx
  src/exodus/internal-router.ts
  src/exodus/main.tsx
  src/exodus/services/home.ts
  src/exodus/services/social/social.d.ts
  src/exodus/utils/accessStorage.ts
Labels: To Review
